// Mirrors the FIELD_LABELS map in public/js/records.js — keep both in sync
// if the quotation form's fields change.
const FIELD_LABELS = {
  proposerName: 'Name (Owner/s)',
  contactNo: 'Contact No.',
  dob1: 'Date of Birth #1',
  dob2: 'Date of Birth #2',
  address: 'Address',
  email: 'Email',
  dpNo: 'DP No/s.',
  issueDate1: 'Issue Date #1',
  expiryDate1: 'Expiry Date #1',
  issueDate2: 'Issue Date #2',
  expiryDate2: 'Expiry Date #2',
  occupation1: 'Occupation/Business #1',
  occupation2: 'Occupation/Business #2',
  make: 'Make',
  model: 'Model',
  useOfVehicle: 'Use of vehicle',
  registrationNo: 'Registration No.',
  yearOfManufacture: 'Year of manufacture',
  seatingCapacity: 'Seating capacity',
  ccHp: 'CC/HP',
  chassisNo: 'Chassis No.',
  engineNo: 'Engine No.',
  typeOfCoverage: 'Type of coverage',
  valueSumInsured: 'Value / Sum insured',
  vehicleMortgaged: 'Vehicle mortgaged',
  financialInstitution: 'Financial institution',
  previousInsurer: 'Previous insurer',
  noClaimDiscountYears: 'No Claim Discount (years)',
  antiTheftDevices: 'Anti-theft devices',
  windscreenLimit: 'Windscreen limit',
  lossOfUse: 'Loss of use',
  waiverOfExcess: 'Waiver of excess',
  personalAccident: 'Personal accident',
  specialPerils: 'Special perils',
  windscreenThirdPartyPrivate: 'Windscreen (TP Private)',
};

module.exports = { FIELD_LABELS };
